homeassistant:
  legacy_triggers: false
  legacy_entity_attributes: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt_bedroom
  server: mqtt://192.168.0.12
  user: mqtt-user
  password: VKNKv85;]y4[XUgG
  keepalive: 60
  reject_unauthorized: true
  version: 5
  include_device_information: false
serial:
  port: /dev/tty.SLAB_USBtoUART
  adapter: auto
frontend:
  port: 8080
advanced:
  pan_id: 711
  channel: 25
  network_key:
    - 3
    - 0
    - 7
    - 10
    - 4
    - 2
    - 0
    - 7
    - 1
    - 0
    - 4
    - 20
    - 7
    - 1
    - 10
    - 4
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_syslog:
    app_name: Bedroom Z2M
    eol: /n
    host: localhost
    localhost: localhost
    path: /var/run/syslog
    pid: process.pid
    port: 51
    protocol: udp4
    type: '5424'
  last_seen: ISO_8601_local
  output: json
  log_level: info
  transmit_power: 9
  adapter_concurrent: 16
  adapter_delay: 0
  ext_pan_id:
    - 237
    - 221
    - 219
    - 221
    - 221
    - 218
    - 221
    - 221
  log_symlink_current: true
device_options:
  legacy: false
  qos: 2
  filtered_attributes:
    - ac_frequency
    - power_factor
  homeassistant:
    ac_frequency: null
    power_factor: null
    battery_low:
      enabled_by_default: false
    linkquality:
      enabled_by_default: true
    last_seen:
      enabled_by_default: true
devices:
  '0x00158d0009414438':
    friendly_name: Bedroom-Multi-Sensor
    homeassistant:
      name: Bedroom Multi-Sensor
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
  '0x282c02bfffeb65a2':
    friendly_name: Bedroom-Keyboard-Light
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Keyboard Light
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
  '0x282c02bfffeb2a16':
    friendly_name: Bedroom-Fan
    filtered_attributes:
      - power_factor
      - ac_frequency
    homeassistant:
      switch:
        type: fan
        object_id: fan
      fan:
        state_value_template: '{{ value_json.state }}'
      battery_low:
        enabled_by_default: false
      linkquality:
        enabled_by_default: true
      name: Bedroom Fan
      last_seen:
        enabled_by_default: true
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 30
    state_action: false
  '0x00124b002a2e95d4':
    friendly_name: Bedroom-Router-South
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Router South
    legacy: false
    optimistic: true
    qos: 2
  '0x00158d000927000e':
    friendly_name: Bedroom-Desk-Button
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Desk Button
      last_seen:
        enabled_by_default: true
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    device_temperature_calibration: 0
    filtered_attributes:
      - ac_frequency
      - power_factor
    retention: 20
  '0xb0ce18140017a83f':
    friendly_name: Bedroom-Desk-Lamp
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Desk Lamp
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
    transition: 1
    color_sync: true
    state_action: false
    filtered_attributes:
      - ac_frequency
      - power_factor
  '0xb0ce181400175010':
    friendly_name: Bedroom-Left-Headboard-Lamp
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Left Headboard Lamp
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
    transition: 1
    color_sync: false
    state_action: false
  '0xb0ce181400176b4c':
    friendly_name: Bedroom-Corner-Lamp
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Corner Lamp
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
    transition: 1
    color_sync: true
    state_action: false
  '0xb0ce18140017ab1b':
    friendly_name: Bedroom-Small-Lamp
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Small Lamp
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
    transition: 1
    color_sync: true
    state_action: false
  '0x000d6f0010e1b077':
    friendly_name: Bedroom-Desk-Sit-Stand-Sensor
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Desk Sit Stand Sensor
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 298
  '0x00158d000836c5c6':
    friendly_name: Cube
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Cube
    legacy: true
    optimistic: true
    qos: 2
  '0xffff000fe7fae16f':
    friendly_name: Bedroom-Dimmer
    legacy: false
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Dimmer
    optimistic: true
    qos: 2
    retain: false
  '0xb0ce1814001748b5':
    friendly_name: Bedroom-Main-Light-Bulb-1
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Main Light Bulb 1
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
    color_sync: true
    state_action: false
    transition: 1
  '0xb0ce18140017d7da':
    friendly_name: Bedroom-Main-Light-Bulb-2
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Main Light Bulb 2
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
    transition: 1
    color_sync: true
    state_action: false
  '0x54ef4410006471ae':
    friendly_name: Bedroom-Presence-Sensor
    disabled: false
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Presence Sensor
    legacy: false
    optimistic: true
    qos: 2
    retain: false
  '0x282c02bfffeb4790':
    friendly_name: TV-Outlet
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: TV Outlet
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
    state_action: false
    power_calibration: 0
  '0x187a3efffe0040e0':
    friendly_name: Living-Room-Presence-Sensor
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Living Room Presence Sensor
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 60
  '0x282c02bfffeb2ddf':
    friendly_name: Bathroom-Fan
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bathroom Fan
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
    state_action: false
  '0xe0798dfffea7b87f':
    friendly_name: Coffee-Table-Button
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Coffee Table Button
    legacy: false
    optimistic: true
    qos: 2
  '0x282c02bfffe84a1a':
    friendly_name: Bedroom-Motion-Sensor-Living-Room-Entrance
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Motion Sensor (Living Room Entrance)
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
    filtered_attributes:
      - ac_frequency
      - power_factor
  '0x282c02bfffe85845':
    friendly_name: Bedroom-Motion-Sensor-Bathroom-Entrance
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bedroom Motion Sensor (Bathroom Entrance)
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
    filtered_attributes:
      - ac_frequency
      - power_factor
  '0xa4c138bc97d6ace1':
    friendly_name: Bathroom-Presence-Sensor
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bathroom Presence Sensor
    legacy: false
    optimistic: true
    qos: 2
  '0xb0ce1814001793c6':
    friendly_name: Bathroom-Overhead-Light
    color_sync: true
    state_action: false
    transition: 1
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bathroom Overhead Light
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
  '0xb0ce18140016db8e':
    friendly_name: Bathroom-Mirror-Bulb-2
    disabled: false
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bathroom Mirror Bulb 2
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
    transition: 1
    color_sync: true
    state_action: false
  '0xb0ce18140016d5ed':
    friendly_name: Bathroom-Mirror-Bulb-3
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bathroom Mirror Bulb 3
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 300
  '0xb0ce18140016e16e':
    friendly_name: Bathroom-Mirror-Bulb-1
    transition: 1
    color_sync: true
    state_action: false
    homeassistant:
      battery_low:
        enabled_by_default: false
      current:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bathroom Mirror Bulb 1
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 299
  '0x00158d0008e031a9':
    friendly_name: Bed-Pressure-Sensor
    filtered_attributes:
      - ac_frequency
      - power_factor
    homeassistant:
      battery_low:
        enabled_by_default: false
      last_seen:
        enabled_by_default: true
      linkquality:
        enabled_by_default: true
      name: Bed Pressure Sensor
    legacy: false
    optimistic: true
    qos: 2
    retain: true
    retention: 28
availability: true
groups:
  '1':
    friendly_name: Bedroom-Main-Light
    transition: 1
    optimistic: true
    qos: 2
    retain: true
    retention: 300
    devices:
      - 0xb0ce1814001748b5/1
      - 0xb0ce18140017d7da/1
